---
- hosts: bergamot
  user: root
  roles:
  - common
  - bergamot-common
  - postgresql93
  - rabbitmq
  - bergamot-data
  - bergamot-agent-manager
  - bergamot-notifier
  - bergamot-worker
  - bergamot-ui
  